#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         8
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true
bspc config focus_follows_pointer	 true
bspc config click_to_focus		 true
bspc config top_padding 48
bspc rule -a \* node=focused split_dir=east
bspc config focused_border_color    '#f0f0f0'
bspc config center_pseudo_tiled 	false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/markus/Pictures/mountain_1.jpg &
compton &
xsetroot -cursor_name left_ptr &
polybar top &
xsetroot -cursor_name left_ptr &
export _JAVA_AWT_WM_NONREPARENTING=1 &
xset -dpms &
xset s off &

